version = 0.1

[default.deploy.parameters]
stack_name = "nps-webcam-gif-generator"
resolve_s3 = true
s3_prefix = "nps-webcam-gif-generator"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
